groups:
- name: up
  rules:
  - alert: up
    expr: probe_success{exported_instance="demo",exported_job="demo"} == 0
    for: 10s
    labels:
      level: critical
    annotations:
      summary: "{{ $labels.app }} is down"
      description: "{{ $labels.app }} has been down for more than 10 seconds."
